### PR TITLE
lab8

### PR DESCRIPTION
**Pull request by Corndogz**

### CODE REVIEW

**Comment by Corndogz** [comment]
Hunter Cornay@Corndogz/lab8

**Comment by adaptiman** [comment]
The format of your change is not correct. Please look at the file and correct the format.

**Comment by Corndogz** [comment]
I'm not exactly sure what I did wrong. How is my format wrong? What can I
do to fix it asap? I apologize for the inconvenience, I just want to make
sure I get the best grade I can for this lab. Thank you.

Hunter Cornay

**Comment by adaptiman** [comment]
The format should be:

David Sweeney@adaptiman/TactileTTS

You originally submitted:

corndogz@Corndogz/LAB8

Until you emailed me, I didn’t know who corndogz was. I see that you have corrected your line to be:

Hunter Cornay@Corndogz/LAB8

Thanks.

--
TTI
David S. Sweeney '88, Ph.D.
Chief Information Officer
Network Information Systems

**Pull request merged**
